-- Create a table for tickets
create table tickets (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  status text check (status in ('open', 'in_progress', 'closed')) default 'open',
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table tickets enable row level security;

-- Create policies
create policy "Users can view their own tickets"
  on tickets for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own tickets"
  on tickets for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own tickets"
  on tickets for update
  using ( auth.uid() = user_id );
