-- Create table for projects
create table projects (
  id bigint generated by default as identity primary key,
  name text not null,
  url text,
  status text check (status in ('active', 'maintenance', 'development', 'archived')) default 'development',
  hosting_renewal_date date,
  image_url text,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for projects
alter table projects enable row level security;

create policy "Users can view their own projects"
  on projects for select
  using ( auth.uid() = user_id );

-- Create table for invoices
create table invoices (
  id bigint generated by default as identity primary key,
  invoice_number text not null,
  service_name text not null,
  amount decimal(10,2) not null,
  currency text default 'USD',
  status text check (status in ('paid', 'pending', 'overdue', 'cancelled')) default 'pending',
  due_date date,
  pdf_url text,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for invoices
alter table invoices enable row level security;

create policy "Users can view their own invoices"
  on invoices for select
  using ( auth.uid() = user_id );

-- Storage Policies (Requires Bucket 'files' to be created in Supabase Dashboard)
-- You must create a bucket named 'files' in the Storage section first.

-- Allow authenticated users to view files in 'files' bucket
-- (You need to run this part in SQL Editor after creating bucket, or set via UI)
-- create policy "Authenticated users can select"
-- on storage.objects for select
-- using ( bucket_id = 'files' and auth.role() = 'authenticated' );

-- create policy "Users can upload their own files"
-- on storage.objects for insert
-- with check ( bucket_id = 'files' and auth.uid() = owner );
